import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type LanguageCode = 'en' | 'hi' | 'ta' | 'te' | 'kn' | 'mr' | 'gu' | 'bn' | 'pa' | 'es' | 'pt' | 'fr' | 'de';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
  languageName: string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LANGUAGES: { code: LanguageCode; name: string; nativeName: string }[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
];

// Translation keys
const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Header
    "app.title": "KISAAN - Analyser",
    "app.subtitle": "Fertilizer Report Reader",
    "app.getStarted": "Get Started",
    "app.goToDashboard": "Go to Dashboard",
    "app.loading": "Loading...",
    
    // Hero
    "hero.title1": "Understand Your Soil,",
    "hero.title2": "Grow Better Crops",
    "hero.description": "Upload your fertilizer reports, get AI-powered analysis, and receive personalized recommendations for improving your fields.",
    "hero.startFree": "Start Free",
    "hero.viewFields": "View Your Fields",
    
    // Features
    "features.title": "Everything You Need",
    "features.npk.title": "NPK Analysis",
    "features.npk.desc": "Track nitrogen, phosphorus, potassium levels with visual gauges and optimal range indicators.",
    "features.ai.title": "AI Recommendations",
    "features.ai.desc": "Get personalized crop suggestions and field improvement techniques powered by AI.",
    "features.multiField.title": "Multi-Field Tracking",
    "features.multiField.desc": "Manage multiple fields and track soil health history with detailed reports.",
    
    // CTA
    "cta.title": "Ready to Improve Your Yields?",
    "cta.description": "Join farmers who are making data-driven decisions for healthier soil.",
    "cta.createAccount": "Create Free Account",
    
    // Footer
    "footer.tagline": "SoilSense — Helping farmers make informed decisions",
    
    // Dashboard
    "dashboard.welcome": "Welcome",
    "dashboard.signOut": "Sign Out",
    "dashboard.yourFields": "Your Fields",
    "dashboard.addField": "Add Field",
    "dashboard.noFields": "No fields yet",
    "dashboard.addFirstField": "Add your first field to get started",
    "dashboard.selectField": "Select a field to view reports",
    "dashboard.reports": "Reports",
    "dashboard.addReport": "Add Report",
    "dashboard.noReports": "No reports yet",
    "dashboard.addFirstReport": "Add your first report to start tracking",
    "dashboard.analyzeWithAI": "Analyze with AI",
    "dashboard.analyzing": "Analyzing...",
    
    // Soil Health
    "soil.health": "Soil Health",
    "soil.nitrogen": "Nitrogen",
    "soil.phosphorus": "Phosphorus",
    "soil.potassium": "Potassium",
    "soil.ph": "pH Level",
    "soil.organicMatter": "Organic Matter",
    "soil.moisture": "Moisture",
    "soil.temperature": "Temperature",
    
    // AI Analysis
    "ai.analysis": "AI Analysis",
    "ai.recommendations": "Recommendations",
    "ai.recommendedCrops": "Recommended Crops",
    "ai.improvementTechniques": "Improvement Techniques",
    "ai.seasonalTips": "Seasonal Tips",
    "ai.npkAnalysis": "NPK Analysis",
    "ai.print": "Print",
    
    // Auth
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.fullName": "Full Name",
    "auth.noAccount": "Don't have an account?",
    "auth.haveAccount": "Already have an account?",
    
    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.acres": "acres",
    "common.location": "Location",
    "common.date": "Date",
    
    // Chatbot
    "chatbot.askQuestion": "Ask your question...",
    "chatbot.aiAssistant": "Agriculture Assistant",
    "chatbot.analyzing": "Thinking...",
    "error": "Error",
    "askQuestion": "Ask your question...",
    "aiAssistant": "Agriculture Assistant",
    "analyzing": "Thinking...",
  },
  hi: {
    "app.title": "किसान - विश्लेषक",
    "app.subtitle": "उर्वरक रिपोर्ट रीडर",
    "app.getStarted": "शुरू करें",
    "app.goToDashboard": "डैशबोर्ड पर जाएं",
    "app.loading": "लोड हो रहा है...",
    "hero.title1": "अपनी मिट्टी को समझें,",
    "hero.title2": "बेहतर फसल उगाएं",
    "hero.description": "अपनी उर्वरक रिपोर्ट अपलोड करें, AI-संचालित विश्लेषण प्राप्त करें, और अपने खेतों को बेहतर बनाने के लिए व्यक्तिगत सिफारिशें प्राप्त करें।",
    "hero.startFree": "मुफ्त शुरू करें",
    "hero.viewFields": "अपने खेत देखें",
    "features.title": "आपको जो चाहिए वह सब",
    "features.npk.title": "NPK विश्लेषण",
    "features.npk.desc": "दृश्य गेज और इष्टतम सीमा संकेतकों के साथ नाइट्रोजन, फास्फोरस, पोटेशियम स्तर ट्रैक करें।",
    "features.ai.title": "AI सिफारिशें",
    "features.ai.desc": "AI द्वारा संचालित व्यक्तिगत फसल सुझाव और खेत सुधार तकनीकें प्राप्त करें।",
    "features.multiField.title": "बहु-खेत ट्रैकिंग",
    "features.multiField.desc": "कई खेतों का प्रबंधन करें और विस्तृत रिपोर्ट के साथ मिट्टी स्वास्थ्य इतिहास ट्रैक करें।",
    "cta.title": "अपनी उपज बढ़ाने के लिए तैयार?",
    "cta.description": "उन किसानों से जुड़ें जो स्वस्थ मिट्टी के लिए डेटा-आधारित निर्णय ले रहे हैं।",
    "cta.createAccount": "मुफ्त खाता बनाएं",
    "footer.tagline": "SoilSense — किसानों को सूचित निर्णय लेने में मदद",
    "dashboard.welcome": "स्वागत है",
    "dashboard.signOut": "साइन आउट",
    "dashboard.yourFields": "आपके खेत",
    "dashboard.addField": "खेत जोड़ें",
    "dashboard.noFields": "अभी कोई खेत नहीं",
    "dashboard.addFirstField": "शुरू करने के लिए अपना पहला खेत जोड़ें",
    "dashboard.selectField": "रिपोर्ट देखने के लिए खेत चुनें",
    "dashboard.reports": "रिपोर्ट",
    "dashboard.addReport": "रिपोर्ट जोड़ें",
    "dashboard.noReports": "अभी कोई रिपोर्ट नहीं",
    "dashboard.addFirstReport": "ट्रैकिंग शुरू करने के लिए अपनी पहली रिपोर्ट जोड़ें",
    "dashboard.analyzeWithAI": "AI से विश्लेषण करें",
    "dashboard.analyzing": "विश्लेषण हो रहा है...",
    "soil.health": "मिट्टी स्वास्थ्य",
    "soil.nitrogen": "नाइट्रोजन",
    "soil.phosphorus": "फास्फोरस",
    "soil.potassium": "पोटेशियम",
    "soil.ph": "pH स्तर",
    "soil.organicMatter": "जैविक पदार्थ",
    "soil.moisture": "नमी",
    "soil.temperature": "तापमान",
    "ai.analysis": "AI विश्लेषण",
    "ai.recommendations": "सिफारिशें",
    "ai.recommendedCrops": "अनुशंसित फसलें",
    "ai.improvementTechniques": "सुधार तकनीकें",
    "ai.seasonalTips": "मौसमी सुझाव",
    "ai.npkAnalysis": "NPK विश्लेषण",
    "ai.print": "प्रिंट करें",
    "auth.signIn": "साइन इन करें",
    "auth.signUp": "साइन अप करें",
    "auth.email": "ईमेल",
    "auth.password": "पासवर्ड",
    "auth.fullName": "पूरा नाम",
    "auth.noAccount": "खाता नहीं है?",
    "auth.haveAccount": "पहले से खाता है?",
    "common.save": "सहेजें",
    "common.cancel": "रद्द करें",
    "common.delete": "हटाएं",
    "common.edit": "संपादित करें",
    "common.loading": "लोड हो रहा है...",
    "common.error": "त्रुटि",
    "common.success": "सफल",
    "common.acres": "एकड़",
    "common.location": "स्थान",
    "common.date": "तारीख",
    
    // Chatbot
    "chatbot.askQuestion": "अपना प्रश्न पूछें...",
    "chatbot.aiAssistant": "कृषि सहायक",
    "chatbot.analyzing": "सोच रहा हूं...",
    "error": "त्रुटि",
    "askQuestion": "अपना प्रश्न पूछें...",
    "aiAssistant": "कृषि सहायक",
    "analyzing": "सोच रहा हूं...",
  },
  ta: {
    "app.title": "கிசான் - பகுப்பாய்வி",
    "app.subtitle": "உர அறிக்கை வாசிப்பான்",
    "app.getStarted": "தொடங்குங்கள்",
    "app.goToDashboard": "டாஷ்போர்டுக்கு செல்",
    "app.loading": "ஏற்றுகிறது...",
    "hero.title1": "உங்கள் மண்ணைப் புரிந்துகொள்ளுங்கள்,",
    "hero.title2": "சிறந்த பயிர்களை வளர்க்கவும்",
    "hero.description": "உங்கள் உர அறிக்கைகளை பதிவேற்றுங்கள், AI-இயங்கும் பகுப்பாய்வைப் பெறுங்கள், உங்கள் வயல்களை மேம்படுத்த தனிப்பயனாக்கப்பட்ட பரிந்துரைகளைப் பெறுங்கள்.",
    "hero.startFree": "இலவசமாக தொடங்குங்கள்",
    "hero.viewFields": "உங்கள் வயல்களைக் காண்க",
    "features.title": "உங்களுக்கு தேவையான அனைத்தும்",
    "features.npk.title": "NPK பகுப்பாய்வு",
    "features.npk.desc": "காட்சி அளவீடுகள் மற்றும் உகந்த வரம்பு குறிகாட்டிகளுடன் நைட்ரஜன், பாஸ்பரஸ், பொட்டாசியம் அளவுகளை கண்காணிக்கவும்.",
    "features.ai.title": "AI பரிந்துரைகள்",
    "features.ai.desc": "AI மூலம் இயக்கப்படும் தனிப்பயனாக்கப்பட்ட பயிர் பரிந்துரைகள் மற்றும் வயல் மேம்பாட்டு நுட்பங்களைப் பெறுங்கள்.",
    "features.multiField.title": "பல-வயல் கண்காணிப்பு",
    "features.multiField.desc": "பல வயல்களை நிர்வகிக்கவும் மற்றும் விரிவான அறிக்கைகளுடன் மண் ஆரோக்கிய வரலாற்றைக் கண்காணிக்கவும்.",
    "cta.title": "உங்கள் விளைச்சலை மேம்படுத்த தயாரா?",
    "cta.description": "ஆரோக்கியமான மண்ணுக்காக தரவு அடிப்படையிலான முடிவுகளை எடுக்கும் விவசாயிகளுடன் இணையுங்கள்.",
    "cta.createAccount": "இலவச கணக்கை உருவாக்கவும்",
    "footer.tagline": "SoilSense — விவசாயிகளுக்கு தகவலறிந்த முடிவுகளை எடுக்க உதவுகிறது",
    "dashboard.welcome": "வரவேற்கிறோம்",
    "dashboard.signOut": "வெளியேறு",
    "dashboard.yourFields": "உங்கள் வயல்கள்",
    "dashboard.addField": "வயல் சேர்க்க",
    "dashboard.noFields": "இன்னும் வயல்கள் இல்லை",
    "dashboard.addFirstField": "தொடங்க உங்கள் முதல் வயலைச் சேர்க்கவும்",
    "dashboard.selectField": "அறிக்கைகளைப் பார்க்க வயலைத் தேர்ந்தெடுக்கவும்",
    "dashboard.reports": "அறிக்கைகள்",
    "dashboard.addReport": "அறிக்கை சேர்க்க",
    "dashboard.noReports": "இன்னும் அறிக்கைகள் இல்லை",
    "dashboard.addFirstReport": "கண்காணிப்பைத் தொடங்க உங்கள் முதல் அறிக்கையைச் சேர்க்கவும்",
    "dashboard.analyzeWithAI": "AI உடன் பகுப்பாய்வு செய்",
    "dashboard.analyzing": "பகுப்பாய்வு செய்கிறது...",
    "soil.health": "மண் ஆரோக்கியம்",
    "soil.nitrogen": "நைட்ரஜன்",
    "soil.phosphorus": "பாஸ்பரஸ்",
    "soil.potassium": "பொட்டாசியம்",
    "soil.ph": "pH நிலை",
    "soil.organicMatter": "கரிம பொருள்",
    "soil.moisture": "ஈரப்பதம்",
    "soil.temperature": "வெப்பநிலை",
    "ai.analysis": "AI பகுப்பாய்வு",
    "ai.recommendations": "பரிந்துரைகள்",
    "ai.recommendedCrops": "பரிந்துரைக்கப்பட்ட பயிர்கள்",
    "ai.improvementTechniques": "மேம்பாட்டு நுட்பங்கள்",
    "ai.seasonalTips": "பருவகால குறிப்புகள்",
    "ai.npkAnalysis": "NPK பகுப்பாய்வு",
    "ai.print": "அச்சிடு",
    "auth.signIn": "உள்நுழைக",
    "auth.signUp": "பதிவு செய்க",
    "auth.email": "மின்னஞ்சல்",
    "auth.password": "கடவுச்சொல்",
    "auth.fullName": "முழு பெயர்",
    "auth.noAccount": "கணக்கு இல்லையா?",
    "auth.haveAccount": "ஏற்கனவே கணக்கு உள்ளதா?",
    "common.save": "சேமி",
    "common.cancel": "ரத்து செய்",
    "common.delete": "நீக்கு",
    "common.edit": "திருத்து",
    "common.loading": "ஏற்றுகிறது...",
    "common.error": "பிழை",
    "common.success": "வெற்றி",
    "common.acres": "ஏக்கர்",
    "common.location": "இடம்",
    "common.date": "தேதி",
  },
  te: {
    "app.title": "కిసాన్ - విశ్లేషకుడు",
    "app.subtitle": "ఎరువుల నివేదిక రీడర్",
    "app.getStarted": "ప్రారంభించండి",
    "app.goToDashboard": "డాష్‌బోర్డ్‌కు వెళ్ళండి",
    "app.loading": "లోడ్ అవుతోంది...",
    "hero.title1": "మీ నేలను అర్థం చేసుకోండి,",
    "hero.title2": "మెరుగైన పంటలు పండించండి",
    "hero.description": "మీ ఎరువుల నివేదికలను అప్‌లోడ్ చేయండి, AI-ఆధారిత విశ్లేషణ పొందండి, మీ పొలాలను మెరుగుపరచడానికి వ్యక్తిగత సిఫార్సులు పొందండి.",
    "hero.startFree": "ఉచితంగా ప్రారంభించండి",
    "hero.viewFields": "మీ పొలాలను చూడండి",
    "features.title": "మీకు కావలసినవన్నీ",
    "features.npk.title": "NPK విశ్లేషణ",
    "features.npk.desc": "విజువల్ గేజ్‌లు మరియు ఆప్టిమల్ రేంజ్ ఇండికేటర్‌లతో నైట్రోజన్, ఫాస్పరస్, పొటాషియం స్థాయిలను ట్రాక్ చేయండి.",
    "features.ai.title": "AI సిఫార్సులు",
    "features.ai.desc": "AI ద్వారా నడిచే వ్యక్తిగత పంట సూచనలు మరియు పొల మెరుగుదల పద్ధతులు పొందండి.",
    "features.multiField.title": "బహుళ-పొల ట్రాకింగ్",
    "features.multiField.desc": "బహుళ పొలాలను నిర్వహించండి మరియు వివరణాత్మక నివేదికలతో నేల ఆరోగ్య చరిత్రను ట్రాక్ చేయండి.",
    "cta.title": "మీ దిగుబడిని మెరుగుపరచడానికి సిద్ధంగా ఉన్నారా?",
    "cta.description": "ఆరోగ్యకరమైన నేల కోసం డేటా-ఆధారిత నిర్ణయాలు తీసుకుంటున్న రైతులతో చేరండి.",
    "cta.createAccount": "ఉచిత ఖాతా సృష్టించండి",
    "footer.tagline": "SoilSense — రైతులకు సమాచారంతో నిర్ణయాలు తీసుకోవడంలో సహాయం",
    "dashboard.welcome": "స్వాగతం",
    "dashboard.signOut": "సైన్ అవుట్",
    "dashboard.yourFields": "మీ పొలాలు",
    "dashboard.addField": "పొలం జోడించండి",
    "dashboard.noFields": "ఇంకా పొలాలు లేవు",
    "dashboard.addFirstField": "ప్రారంభించడానికి మీ మొదటి పొలాన్ని జోడించండి",
    "dashboard.selectField": "నివేదికలను చూడటానికి పొలాన్ని ఎంచుకోండి",
    "dashboard.reports": "నివేదికలు",
    "dashboard.addReport": "నివేదిక జోడించండి",
    "dashboard.noReports": "ఇంకా నివేదికలు లేవు",
    "dashboard.addFirstReport": "ట్రాకింగ్ ప్రారంభించడానికి మీ మొదటి నివేదికను జోడించండి",
    "dashboard.analyzeWithAI": "AI తో విశ్లేషించండి",
    "dashboard.analyzing": "విశ్లేషిస్తోంది...",
    "soil.health": "నేల ఆరోగ్యం",
    "soil.nitrogen": "నైట్రోజన్",
    "soil.phosphorus": "ఫాస్పరస్",
    "soil.potassium": "పొటాషియం",
    "soil.ph": "pH స్థాయి",
    "soil.organicMatter": "సేంద్రీయ పదార్థం",
    "soil.moisture": "తేమ",
    "soil.temperature": "ఉష్ణోగ్రత",
    "ai.analysis": "AI విశ్లేషణ",
    "ai.recommendations": "సిఫార్సులు",
    "ai.recommendedCrops": "సిఫార్సు చేయబడిన పంటలు",
    "ai.improvementTechniques": "మెరుగుదల పద్ధతులు",
    "ai.seasonalTips": "సీజనల్ చిట్కాలు",
    "ai.npkAnalysis": "NPK విశ్లేషణ",
    "ai.print": "ప్రింట్",
    "auth.signIn": "సైన్ ఇన్",
    "auth.signUp": "సైన్ అప్",
    "auth.email": "ఇమెయిల్",
    "auth.password": "పాస్‌వర్డ్",
    "auth.fullName": "పూర్తి పేరు",
    "auth.noAccount": "ఖాతా లేదా?",
    "auth.haveAccount": "ఇప్పటికే ఖాతా ఉందా?",
    "common.save": "సేవ్ చేయండి",
    "common.cancel": "రద్దు చేయండి",
    "common.delete": "తొలగించండి",
    "common.edit": "సవరించండి",
    "common.loading": "లోడ్ అవుతోంది...",
    "common.error": "లోపం",
    "common.success": "విజయం",
    "common.acres": "ఎకరాలు",
    "common.location": "స్థానం",
    "common.date": "తేదీ",
  },
  kn: {
    "app.title": "ಕಿಸಾನ್ - ವಿಶ್ಲೇಷಕ",
    "app.subtitle": "ರಸಗೊಬ್ಬರ ವರದಿ ರೀಡರ್",
    "app.getStarted": "ಪ್ರಾರಂಭಿಸಿ",
    "app.goToDashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ",
    "app.loading": "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    "hero.title1": "ನಿಮ್ಮ ಮಣ್ಣನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ,",
    "hero.title2": "ಉತ್ತಮ ಬೆಳೆಗಳನ್ನು ಬೆಳೆಸಿ",
    "hero.description": "ನಿಮ್ಮ ರಸಗೊಬ್ಬರ ವರದಿಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ, AI-ಚಾಲಿತ ವಿಶ್ಲೇಷಣೆ ಪಡೆಯಿರಿ, ನಿಮ್ಮ ಹೊಲಗಳನ್ನು ಸುಧಾರಿಸಲು ವೈಯಕ್ತಿಕ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ.",
    "hero.startFree": "ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ",
    "hero.viewFields": "ನಿಮ್ಮ ಹೊಲಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    "features.title": "ನಿಮಗೆ ಬೇಕಾದ ಎಲ್ಲವೂ",
    "features.npk.title": "NPK ವಿಶ್ಲೇಷಣೆ",
    "features.npk.desc": "ದೃಶ್ಯ ಗೇಜ್‌ಗಳು ಮತ್ತು ಅನುಕೂಲ ಶ್ರೇಣಿ ಸೂಚಕಗಳೊಂದಿಗೆ ಸಾರಜನಕ, ರಂಜಕ, ಪೊಟ್ಯಾಸಿಯಂ ಮಟ್ಟಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
    "features.ai.title": "AI ಶಿಫಾರಸುಗಳು",
    "features.ai.desc": "AI ಚಾಲಿತ ವೈಯಕ್ತಿಕ ಬೆಳೆ ಸಲಹೆಗಳು ಮತ್ತು ಹೊಲ ಸುಧಾರಣಾ ತಂತ್ರಗಳನ್ನು ಪಡೆಯಿರಿ.",
    "features.multiField.title": "ಬಹು-ಹೊಲ ಟ್ರ್ಯಾಕಿಂಗ್",
    "features.multiField.desc": "ಬಹು ಹೊಲಗಳನ್ನು ನಿರ್ವಹಿಸಿ ಮತ್ತು ವಿವರವಾದ ವರದಿಗಳೊಂದಿಗೆ ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಇತಿಹಾಸವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
    "cta.title": "ನಿಮ್ಮ ಇಳುವರಿಯನ್ನು ಸುಧಾರಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?",
    "cta.description": "ಆರೋಗ್ಯಕರ ಮಣ್ಣಿಗಾಗಿ ಡೇಟಾ-ಆಧಾರಿತ ನಿರ್ಧಾರಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳುತ್ತಿರುವ ರೈತರೊಂದಿಗೆ ಸೇರಿ.",
    "cta.createAccount": "ಉಚಿತ ಖಾತೆ ರಚಿಸಿ",
    "footer.tagline": "SoilSense — ರೈತರಿಗೆ ತಿಳುವಳಿಕೆಯುಳ್ಳ ನಿರ್ಧಾರಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಲು ಸಹಾಯ",
    "dashboard.welcome": "ಸ್ವಾಗತ",
    "dashboard.signOut": "ಸೈನ್ ಔಟ್",
    "dashboard.yourFields": "ನಿಮ್ಮ ಹೊಲಗಳು",
    "dashboard.addField": "ಹೊಲ ಸೇರಿಸಿ",
    "dashboard.noFields": "ಇನ್ನೂ ಹೊಲಗಳಿಲ್ಲ",
    "dashboard.addFirstField": "ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಮೊದಲ ಹೊಲವನ್ನು ಸೇರಿಸಿ",
    "dashboard.selectField": "ವರದಿಗಳನ್ನು ವೀಕ್ಷಿಸಲು ಹೊಲವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "dashboard.reports": "ವರದಿಗಳು",
    "dashboard.addReport": "ವರದಿ ಸೇರಿಸಿ",
    "dashboard.noReports": "ಇನ್ನೂ ವರದಿಗಳಿಲ್ಲ",
    "dashboard.addFirstReport": "ಟ್ರ್ಯಾಕಿಂಗ್ ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಮೊದಲ ವರದಿಯನ್ನು ಸೇರಿಸಿ",
    "dashboard.analyzeWithAI": "AI ನೊಂದಿಗೆ ವಿಶ್ಲೇಷಿಸಿ",
    "dashboard.analyzing": "ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...",
    "soil.health": "ಮಣ್ಣಿನ ಆರೋಗ್ಯ",
    "soil.nitrogen": "ಸಾರಜನಕ",
    "soil.phosphorus": "ರಂಜಕ",
    "soil.potassium": "ಪೊಟ್ಯಾಸಿಯಂ",
    "soil.ph": "pH ಮಟ್ಟ",
    "soil.organicMatter": "ಸಾವಯವ ವಸ್ತು",
    "soil.moisture": "ತೇವಾಂಶ",
    "soil.temperature": "ತಾಪಮಾನ",
    "ai.analysis": "AI ವಿಶ್ಲೇಷಣೆ",
    "ai.recommendations": "ಶಿಫಾರಸುಗಳು",
    "ai.recommendedCrops": "ಶಿಫಾರಸು ಮಾಡಿದ ಬೆಳೆಗಳು",
    "ai.improvementTechniques": "ಸುಧಾರಣಾ ತಂತ್ರಗಳು",
    "ai.seasonalTips": "ಋತುಮಾನದ ಸಲಹೆಗಳು",
    "ai.npkAnalysis": "NPK ವಿಶ್ಲೇಷಣೆ",
    "ai.print": "ಮುದ್ರಿಸಿ",
    "auth.signIn": "ಸೈನ್ ಇನ್",
    "auth.signUp": "ಸೈನ್ ಅಪ್",
    "auth.email": "ಇಮೇಲ್",
    "auth.password": "ಪಾಸ್‌ವರ್ಡ್",
    "auth.fullName": "ಪೂರ್ಣ ಹೆಸರು",
    "auth.noAccount": "ಖಾತೆ ಇಲ್ಲವೇ?",
    "auth.haveAccount": "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
    "common.save": "ಉಳಿಸಿ",
    "common.cancel": "ರದ್ದುಮಾಡಿ",
    "common.delete": "ಅಳಿಸಿ",
    "common.edit": "ತಿದ್ದಿ",
    "common.loading": "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    "common.error": "ದೋಷ",
    "common.success": "ಯಶಸ್ಸು",
    "common.acres": "ಎಕರೆ",
    "common.location": "ಸ್ಥಳ",
    "common.date": "ದಿನಾಂಕ",
  },
  mr: {
    "app.title": "किसान - विश्लेषक",
    "app.subtitle": "खत अहवाल वाचक",
    "app.getStarted": "सुरू करा",
    "app.goToDashboard": "डॅशबोर्डवर जा",
    "app.loading": "लोड होत आहे...",
    "hero.title1": "तुमची माती समजून घ्या,",
    "hero.title2": "चांगली पिके घ्या",
    "hero.description": "तुमचे खत अहवाल अपलोड करा, AI-चालित विश्लेषण मिळवा आणि तुमच्या शेतात सुधारणा करण्यासाठी वैयक्तिक शिफारसी मिळवा.",
    "hero.startFree": "मोफत सुरू करा",
    "hero.viewFields": "तुमची शेती पहा",
    "features.title": "तुम्हाला हवे ते सर्व",
    "features.npk.title": "NPK विश्लेषण",
    "features.npk.desc": "व्हिज्युअल गेज आणि इष्टतम श्रेणी निर्देशकांसह नायट्रोजन, फॉस्फरस, पोटॅशियम पातळी ट्रॅक करा.",
    "features.ai.title": "AI शिफारसी",
    "features.ai.desc": "AI द्वारे चालित वैयक्तिक पीक सूचना आणि शेत सुधारणा तंत्रे मिळवा.",
    "features.multiField.title": "बहु-शेत ट्रॅकिंग",
    "features.multiField.desc": "अनेक शेतांचे व्यवस्थापन करा आणि तपशीलवार अहवालांसह माती आरोग्य इतिहास ट्रॅक करा.",
    "cta.title": "तुमचे उत्पादन वाढवायला तयार आहात?",
    "cta.description": "निरोगी मातीसाठी डेटा-आधारित निर्णय घेणाऱ्या शेतकऱ्यांसोबत सामील व्हा.",
    "cta.createAccount": "मोफत खाते तयार करा",
    "footer.tagline": "SoilSense — शेतकऱ्यांना माहितीपूर्ण निर्णय घेण्यास मदत",
    "dashboard.welcome": "स्वागत",
    "dashboard.signOut": "साइन आउट",
    "dashboard.yourFields": "तुमची शेती",
    "dashboard.addField": "शेत जोडा",
    "dashboard.noFields": "अजून शेती नाही",
    "dashboard.addFirstField": "सुरू करण्यासाठी तुमचे पहिले शेत जोडा",
    "dashboard.selectField": "अहवाल पाहण्यासाठी शेत निवडा",
    "dashboard.reports": "अहवाल",
    "dashboard.addReport": "अहवाल जोडा",
    "dashboard.noReports": "अजून अहवाल नाहीत",
    "dashboard.addFirstReport": "ट्रॅकिंग सुरू करण्यासाठी तुमचा पहिला अहवाल जोडा",
    "dashboard.analyzeWithAI": "AI सह विश्लेषण करा",
    "dashboard.analyzing": "विश्लेषण होत आहे...",
    "soil.health": "माती आरोग्य",
    "soil.nitrogen": "नायट्रोजन",
    "soil.phosphorus": "फॉस्फरस",
    "soil.potassium": "पोटॅशियम",
    "soil.ph": "pH पातळी",
    "soil.organicMatter": "सेंद्रिय पदार्थ",
    "soil.moisture": "आर्द्रता",
    "soil.temperature": "तापमान",
    "ai.analysis": "AI विश्लेषण",
    "ai.recommendations": "शिफारसी",
    "ai.recommendedCrops": "शिफारस केलेली पिके",
    "ai.improvementTechniques": "सुधारणा तंत्रे",
    "ai.seasonalTips": "हंगामी टिप्स",
    "ai.npkAnalysis": "NPK विश्लेषण",
    "ai.print": "प्रिंट करा",
    "auth.signIn": "साइन इन करा",
    "auth.signUp": "साइन अप करा",
    "auth.email": "ईमेल",
    "auth.password": "पासवर्ड",
    "auth.fullName": "पूर्ण नाव",
    "auth.noAccount": "खाते नाही?",
    "auth.haveAccount": "आधीच खाते आहे?",
    "common.save": "जतन करा",
    "common.cancel": "रद्द करा",
    "common.delete": "हटवा",
    "common.edit": "संपादित करा",
    "common.loading": "लोड होत आहे...",
    "common.error": "त्रुटी",
    "common.success": "यशस्वी",
    "common.acres": "एकर",
    "common.location": "स्थान",
    "common.date": "तारीख",
  },
  gu: {
    "app.title": "કિસાન - વિશ્લેષક",
    "app.subtitle": "ખાતર અહેવાલ વાચક",
    "app.getStarted": "શરૂ કરો",
    "app.goToDashboard": "ડેશબોર્ડ પર જાઓ",
    "app.loading": "લોડ થઈ રહ્યું છે...",
    "hero.title1": "તમારી જમીન સમજો,",
    "hero.title2": "સારા પાક ઉગાડો",
    "hero.description": "તમારા ખાતર અહેવાલો અપલોડ કરો, AI-સંચાલિત વિશ્લેષણ મેળવો, અને તમારા ખેતરોને સુધારવા માટે વ્યક્તિગત ભલામણો મેળવો.",
    "hero.startFree": "મફત શરૂ કરો",
    "hero.viewFields": "તમારા ખેતરો જુઓ",
    "features.title": "તમને જોઈએ તે બધું",
    "features.npk.title": "NPK વિશ્લેષણ",
    "features.npk.desc": "વિઝ્યુઅલ ગેજ અને શ્રેષ્ઠ શ્રેણી સૂચકાંકો સાથે નાઇટ્રોજન, ફોસ્ફરસ, પોટેશિયમ સ્તરો ટ્રેક કરો.",
    "features.ai.title": "AI ભલામણો",
    "features.ai.desc": "AI દ્વારા સંચાલિત વ્યક્તિગત પાક સૂચનો અને ખેતર સુધારણા તકનીકો મેળવો.",
    "features.multiField.title": "બહુ-ખેતર ટ્રેકિંગ",
    "features.multiField.desc": "બહુવિધ ખેતરોનું સંચાલન કરો અને વિગતવાર અહેવાલો સાથે જમીન આરોગ્ય ઇતિહાસ ટ્રેક કરો.",
    "cta.title": "તમારી ઉપજ સુધારવા તૈયાર છો?",
    "cta.description": "તંદુરસ્ત જમીન માટે ડેટા-આધારિત નિર્ણયો લેતા ખેડૂતો સાથે જોડાઓ.",
    "cta.createAccount": "મફત ખાતું બનાવો",
    "footer.tagline": "SoilSense — ખેડૂતોને માહિતગાર નિર્ણયો લેવામાં મદદ",
    "dashboard.welcome": "સ્વાગત છે",
    "dashboard.signOut": "સાઇન આઉટ",
    "dashboard.yourFields": "તમારા ખેતરો",
    "dashboard.addField": "ખેતર ઉમેરો",
    "dashboard.noFields": "હજુ કોઈ ખેતર નથી",
    "dashboard.addFirstField": "શરૂ કરવા માટે તમારું પ્રથમ ખેતર ઉમેરો",
    "dashboard.selectField": "અહેવાલો જોવા માટે ખેતર પસંદ કરો",
    "dashboard.reports": "અહેવાલો",
    "dashboard.addReport": "અહેવાલ ઉમેરો",
    "dashboard.noReports": "હજુ કોઈ અહેવાલ નથી",
    "dashboard.addFirstReport": "ટ્રેકિંગ શરૂ કરવા માટે તમારો પ્રથમ અહેવાલ ઉમેરો",
    "dashboard.analyzeWithAI": "AI સાથે વિશ્લેષણ કરો",
    "dashboard.analyzing": "વિશ્લેષણ થઈ રહ્યું છે...",
    "soil.health": "જમીન આરોગ્ય",
    "soil.nitrogen": "નાઇટ્રોજન",
    "soil.phosphorus": "ફોસ્ફરસ",
    "soil.potassium": "પોટેશિયમ",
    "soil.ph": "pH સ્તર",
    "soil.organicMatter": "કાર્બનિક પદાર્થ",
    "soil.moisture": "ભેજ",
    "soil.temperature": "તાપમાન",
    "ai.analysis": "AI વિશ્લેષણ",
    "ai.recommendations": "ભલામણો",
    "ai.recommendedCrops": "ભલામણ કરેલ પાક",
    "ai.improvementTechniques": "સુધારણા તકનીકો",
    "ai.seasonalTips": "મોસમી ટિપ્સ",
    "ai.npkAnalysis": "NPK વિશ્લેષણ",
    "ai.print": "પ્રિન્ટ કરો",
    "auth.signIn": "સાઇન ઇન",
    "auth.signUp": "સાઇન અપ",
    "auth.email": "ઇમેઇલ",
    "auth.password": "પાસવર્ડ",
    "auth.fullName": "પૂરું નામ",
    "auth.noAccount": "ખાતું નથી?",
    "auth.haveAccount": "પહેલેથી ખાતું છે?",
    "common.save": "સાચવો",
    "common.cancel": "રદ કરો",
    "common.delete": "કાઢી નાખો",
    "common.edit": "સંપાદિત કરો",
    "common.loading": "લોડ થઈ રહ્યું છે...",
    "common.error": "ભૂલ",
    "common.success": "સફળ",
    "common.acres": "એકર",
    "common.location": "સ્થાન",
    "common.date": "તારીખ",
  },
  bn: {
    "app.title": "কিষাণ - বিশ্লেষক",
    "app.subtitle": "সার প্রতিবেদন পাঠক",
    "app.getStarted": "শুরু করুন",
    "app.goToDashboard": "ড্যাশবোর্ডে যান",
    "app.loading": "লোড হচ্ছে...",
    "hero.title1": "আপনার মাটি বুঝুন,",
    "hero.title2": "ভালো ফসল ফলান",
    "hero.description": "আপনার সার প্রতিবেদন আপলোড করুন, AI-চালিত বিশ্লেষণ পান এবং আপনার ক্ষেত্র উন্নত করতে ব্যক্তিগত সুপারিশ পান।",
    "hero.startFree": "বিনামূল্যে শুরু করুন",
    "hero.viewFields": "আপনার ক্ষেত্র দেখুন",
    "features.title": "আপনার যা দরকার সব",
    "features.npk.title": "NPK বিশ্লেষণ",
    "features.npk.desc": "ভিজ্যুয়াল গেজ এবং সর্বোত্তম পরিসীমা সূচক দিয়ে নাইট্রোজেন, ফসফরাস, পটাসিয়াম স্তর ট্র্যাক করুন।",
    "features.ai.title": "AI সুপারিশ",
    "features.ai.desc": "AI দ্বারা চালিত ব্যক্তিগত ফসল পরামর্শ এবং ক্ষেত্র উন্নয়ন কৌশল পান।",
    "features.multiField.title": "বহু-ক্ষেত্র ট্র্যাকিং",
    "features.multiField.desc": "একাধিক ক্ষেত্র পরিচালনা করুন এবং বিস্তারিত প্রতিবেদনের সাথে মাটির স্বাস্থ্য ইতিহাস ট্র্যাক করুন।",
    "cta.title": "আপনার ফলন উন্নত করতে প্রস্তুত?",
    "cta.description": "স্বাস্থ্যকর মাটির জন্য ডেটা-চালিত সিদ্ধান্ত নেওয়া কৃষকদের সাথে যোগ দিন।",
    "cta.createAccount": "বিনামূল্যে অ্যাকাউন্ট তৈরি করুন",
    "footer.tagline": "SoilSense — কৃষকদের সচেতন সিদ্ধান্ত নিতে সাহায্য করে",
    "dashboard.welcome": "স্বাগতম",
    "dashboard.signOut": "সাইন আউট",
    "dashboard.yourFields": "আপনার ক্ষেত্র",
    "dashboard.addField": "ক্ষেত্র যোগ করুন",
    "dashboard.noFields": "এখনও কোনো ক্ষেত্র নেই",
    "dashboard.addFirstField": "শুরু করতে আপনার প্রথম ক্ষেত্র যোগ করুন",
    "dashboard.selectField": "প্রতিবেদন দেখতে ক্ষেত্র নির্বাচন করুন",
    "dashboard.reports": "প্রতিবেদন",
    "dashboard.addReport": "প্রতিবেদন যোগ করুন",
    "dashboard.noReports": "এখনও কোনো প্রতিবেদন নেই",
    "dashboard.addFirstReport": "ট্র্যাকিং শুরু করতে আপনার প্রথম প্রতিবেদন যোগ করুন",
    "dashboard.analyzeWithAI": "AI দিয়ে বিশ্লেষণ করুন",
    "dashboard.analyzing": "বিশ্লেষণ হচ্ছে...",
    "soil.health": "মাটির স্বাস্থ্য",
    "soil.nitrogen": "নাইট্রোজেন",
    "soil.phosphorus": "ফসফরাস",
    "soil.potassium": "পটাসিয়াম",
    "soil.ph": "pH স্তর",
    "soil.organicMatter": "জৈব পদার্থ",
    "soil.moisture": "আর্দ্রতা",
    "soil.temperature": "তাপমাত্রা",
    "ai.analysis": "AI বিশ্লেষণ",
    "ai.recommendations": "সুপারিশ",
    "ai.recommendedCrops": "সুপারিশকৃত ফসল",
    "ai.improvementTechniques": "উন্নয়ন কৌশল",
    "ai.seasonalTips": "মৌসুমী পরামর্শ",
    "ai.npkAnalysis": "NPK বিশ্লেষণ",
    "ai.print": "প্রিন্ট",
    "auth.signIn": "সাইন ইন",
    "auth.signUp": "সাইন আপ",
    "auth.email": "ইমেইল",
    "auth.password": "পাসওয়ার্ড",
    "auth.fullName": "পুরো নাম",
    "auth.noAccount": "অ্যাকাউন্ট নেই?",
    "auth.haveAccount": "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    "common.save": "সংরক্ষণ করুন",
    "common.cancel": "বাতিল",
    "common.delete": "মুছুন",
    "common.edit": "সম্পাদনা",
    "common.loading": "লোড হচ্ছে...",
    "common.error": "ত্রুটি",
    "common.success": "সফল",
    "common.acres": "একর",
    "common.location": "অবস্থান",
    "common.date": "তারিখ",
  },
  pa: {
    "app.title": "ਕਿਸਾਨ - ਵਿਸ਼ਲੇਸ਼ਕ",
    "app.subtitle": "ਖਾਦ ਰਿਪੋਰਟ ਰੀਡਰ",
    "app.getStarted": "ਸ਼ੁਰੂ ਕਰੋ",
    "app.goToDashboard": "ਡੈਸ਼ਬੋਰਡ 'ਤੇ ਜਾਓ",
    "app.loading": "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    "hero.title1": "ਆਪਣੀ ਮਿੱਟੀ ਨੂੰ ਸਮਝੋ,",
    "hero.title2": "ਬਿਹਤਰ ਫਸਲਾਂ ਉਗਾਓ",
    "hero.description": "ਆਪਣੀਆਂ ਖਾਦ ਰਿਪੋਰਟਾਂ ਅੱਪਲੋਡ ਕਰੋ, AI-ਸੰਚਾਲਿਤ ਵਿਸ਼ਲੇਸ਼ਣ ਪ੍ਰਾਪਤ ਕਰੋ, ਅਤੇ ਆਪਣੇ ਖੇਤਾਂ ਨੂੰ ਬਿਹਤਰ ਬਣਾਉਣ ਲਈ ਨਿੱਜੀ ਸਿਫਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰੋ।",
    "hero.startFree": "ਮੁਫ਼ਤ ਸ਼ੁਰੂ ਕਰੋ",
    "hero.viewFields": "ਆਪਣੇ ਖੇਤ ਵੇਖੋ",
    "features.title": "ਤੁਹਾਨੂੰ ਲੋੜੀਂਦਾ ਸਭ ਕੁਝ",
    "features.npk.title": "NPK ਵਿਸ਼ਲੇਸ਼ਣ",
    "features.npk.desc": "ਵਿਜ਼ੂਅਲ ਗੇਜ ਅਤੇ ਅਨੁਕੂਲ ਰੇਂਜ ਸੂਚਕਾਂ ਨਾਲ ਨਾਈਟ੍ਰੋਜਨ, ਫਾਸਫੋਰਸ, ਪੋਟਾਸ਼ੀਅਮ ਪੱਧਰਾਂ ਨੂੰ ਟ੍ਰੈਕ ਕਰੋ।",
    "features.ai.title": "AI ਸਿਫਾਰਸ਼ਾਂ",
    "features.ai.desc": "AI ਦੁਆਰਾ ਸੰਚਾਲਿਤ ਨਿੱਜੀ ਫਸਲ ਸੁਝਾਅ ਅਤੇ ਖੇਤ ਸੁਧਾਰ ਤਕਨੀਕਾਂ ਪ੍ਰਾਪਤ ਕਰੋ।",
    "features.multiField.title": "ਬਹੁ-ਖੇਤ ਟ੍ਰੈਕਿੰਗ",
    "features.multiField.desc": "ਕਈ ਖੇਤਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ ਅਤੇ ਵਿਸਤ੍ਰਿਤ ਰਿਪੋਰਟਾਂ ਨਾਲ ਮਿੱਟੀ ਦੀ ਸਿਹਤ ਇਤਿਹਾਸ ਟ੍ਰੈਕ ਕਰੋ।",
    "cta.title": "ਆਪਣੀ ਪੈਦਾਵਾਰ ਵਧਾਉਣ ਲਈ ਤਿਆਰ ਹੋ?",
    "cta.description": "ਸਿਹਤਮੰਦ ਮਿੱਟੀ ਲਈ ਡਾਟਾ-ਅਧਾਰਿਤ ਫੈਸਲੇ ਲੈਣ ਵਾਲੇ ਕਿਸਾਨਾਂ ਨਾਲ ਜੁੜੋ।",
    "cta.createAccount": "ਮੁਫ਼ਤ ਖਾਤਾ ਬਣਾਓ",
    "footer.tagline": "SoilSense — ਕਿਸਾਨਾਂ ਨੂੰ ਸੂਚਿਤ ਫੈਸਲੇ ਲੈਣ ਵਿੱਚ ਮਦਦ",
    "dashboard.welcome": "ਜੀ ਆਇਆਂ ਨੂੰ",
    "dashboard.signOut": "ਸਾਈਨ ਆਊਟ",
    "dashboard.yourFields": "ਤੁਹਾਡੇ ਖੇਤ",
    "dashboard.addField": "ਖੇਤ ਜੋੜੋ",
    "dashboard.noFields": "ਅਜੇ ਕੋਈ ਖੇਤ ਨਹੀਂ",
    "dashboard.addFirstField": "ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਆਪਣਾ ਪਹਿਲਾ ਖੇਤ ਜੋੜੋ",
    "dashboard.selectField": "ਰਿਪੋਰਟਾਂ ਵੇਖਣ ਲਈ ਖੇਤ ਚੁਣੋ",
    "dashboard.reports": "ਰਿਪੋਰਟਾਂ",
    "dashboard.addReport": "ਰਿਪੋਰਟ ਜੋੜੋ",
    "dashboard.noReports": "ਅਜੇ ਕੋਈ ਰਿਪੋਰਟ ਨਹੀਂ",
    "dashboard.addFirstReport": "ਟ੍ਰੈਕਿੰਗ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਆਪਣੀ ਪਹਿਲੀ ਰਿਪੋਰਟ ਜੋੜੋ",
    "dashboard.analyzeWithAI": "AI ਨਾਲ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
    "dashboard.analyzing": "ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...",
    "soil.health": "ਮਿੱਟੀ ਦੀ ਸਿਹਤ",
    "soil.nitrogen": "ਨਾਈਟ੍ਰੋਜਨ",
    "soil.phosphorus": "ਫਾਸਫੋਰਸ",
    "soil.potassium": "ਪੋਟਾਸ਼ੀਅਮ",
    "soil.ph": "pH ਪੱਧਰ",
    "soil.organicMatter": "ਜੈਵਿਕ ਪਦਾਰਥ",
    "soil.moisture": "ਨਮੀ",
    "soil.temperature": "ਤਾਪਮਾਨ",
    "ai.analysis": "AI ਵਿਸ਼ਲੇਸ਼ਣ",
    "ai.recommendations": "ਸਿਫਾਰਸ਼ਾਂ",
    "ai.recommendedCrops": "ਸਿਫਾਰਸ਼ੀ ਫਸਲਾਂ",
    "ai.improvementTechniques": "ਸੁਧਾਰ ਤਕਨੀਕਾਂ",
    "ai.seasonalTips": "ਮੌਸਮੀ ਸੁਝਾਅ",
    "ai.npkAnalysis": "NPK ਵਿਸ਼ਲੇਸ਼ਣ",
    "ai.print": "ਪ੍ਰਿੰਟ ਕਰੋ",
    "auth.signIn": "ਸਾਈਨ ਇਨ",
    "auth.signUp": "ਸਾਈਨ ਅੱਪ",
    "auth.email": "ਈਮੇਲ",
    "auth.password": "ਪਾਸਵਰਡ",
    "auth.fullName": "ਪੂਰਾ ਨਾਮ",
    "auth.noAccount": "ਖਾਤਾ ਨਹੀਂ ਹੈ?",
    "auth.haveAccount": "ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?",
    "common.save": "ਸੇਵ ਕਰੋ",
    "common.cancel": "ਰੱਦ ਕਰੋ",
    "common.delete": "ਮਿਟਾਓ",
    "common.edit": "ਸੋਧੋ",
    "common.loading": "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    "common.error": "ਗਲਤੀ",
    "common.success": "ਸਫਲ",
    "common.acres": "ਏਕੜ",
    "common.location": "ਸਥਾਨ",
    "common.date": "ਤਾਰੀਖ",
  },
  es: {
    "app.title": "KISAAN - Analizador",
    "app.subtitle": "Lector de Informes de Fertilizantes",
    "app.getStarted": "Comenzar",
    "app.goToDashboard": "Ir al Panel",
    "app.loading": "Cargando...",
    "hero.title1": "Entiende Tu Suelo,",
    "hero.title2": "Cultiva Mejores Cosechas",
    "hero.description": "Sube tus informes de fertilizantes, obtén análisis con IA y recibe recomendaciones personalizadas para mejorar tus campos.",
    "hero.startFree": "Comenzar Gratis",
    "hero.viewFields": "Ver Tus Campos",
    "features.title": "Todo Lo Que Necesitas",
    "features.npk.title": "Análisis NPK",
    "features.npk.desc": "Rastrea los niveles de nitrógeno, fósforo y potasio con medidores visuales e indicadores de rango óptimo.",
    "features.ai.title": "Recomendaciones IA",
    "features.ai.desc": "Obtén sugerencias personalizadas de cultivos y técnicas de mejora impulsadas por IA.",
    "features.multiField.title": "Seguimiento Multi-Campo",
    "features.multiField.desc": "Administra múltiples campos y rastrea el historial de salud del suelo con informes detallados.",
    "cta.title": "¿Listo para Mejorar Tus Rendimientos?",
    "cta.description": "Únete a agricultores que toman decisiones basadas en datos para un suelo más saludable.",
    "cta.createAccount": "Crear Cuenta Gratis",
    "footer.tagline": "SoilSense — Ayudando a agricultores a tomar decisiones informadas",
    "dashboard.welcome": "Bienvenido",
    "dashboard.signOut": "Cerrar Sesión",
    "dashboard.yourFields": "Tus Campos",
    "dashboard.addField": "Agregar Campo",
    "dashboard.noFields": "Sin campos aún",
    "dashboard.addFirstField": "Agrega tu primer campo para comenzar",
    "dashboard.selectField": "Selecciona un campo para ver informes",
    "dashboard.reports": "Informes",
    "dashboard.addReport": "Agregar Informe",
    "dashboard.noReports": "Sin informes aún",
    "dashboard.addFirstReport": "Agrega tu primer informe para comenzar",
    "dashboard.analyzeWithAI": "Analizar con IA",
    "dashboard.analyzing": "Analizando...",
    "soil.health": "Salud del Suelo",
    "soil.nitrogen": "Nitrógeno",
    "soil.phosphorus": "Fósforo",
    "soil.potassium": "Potasio",
    "soil.ph": "Nivel de pH",
    "soil.organicMatter": "Materia Orgánica",
    "soil.moisture": "Humedad",
    "soil.temperature": "Temperatura",
    "ai.analysis": "Análisis IA",
    "ai.recommendations": "Recomendaciones",
    "ai.recommendedCrops": "Cultivos Recomendados",
    "ai.improvementTechniques": "Técnicas de Mejora",
    "ai.seasonalTips": "Consejos Estacionales",
    "ai.npkAnalysis": "Análisis NPK",
    "ai.print": "Imprimir",
    "auth.signIn": "Iniciar Sesión",
    "auth.signUp": "Registrarse",
    "auth.email": "Correo",
    "auth.password": "Contraseña",
    "auth.fullName": "Nombre Completo",
    "auth.noAccount": "¿No tienes cuenta?",
    "auth.haveAccount": "¿Ya tienes cuenta?",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.acres": "acres",
    "common.location": "Ubicación",
    "common.date": "Fecha",
  },
  pt: {
    "app.title": "KISAAN - Analisador",
    "app.subtitle": "Leitor de Relatórios de Fertilizantes",
    "app.getStarted": "Começar",
    "app.goToDashboard": "Ir para o Painel",
    "app.loading": "Carregando...",
    "hero.title1": "Entenda Seu Solo,",
    "hero.title2": "Cultive Melhores Safras",
    "hero.description": "Carregue seus relatórios de fertilizantes, obtenha análises com IA e receba recomendações personalizadas para melhorar seus campos.",
    "hero.startFree": "Começar Grátis",
    "hero.viewFields": "Ver Seus Campos",
    "features.title": "Tudo Que Você Precisa",
    "features.npk.title": "Análise NPK",
    "features.npk.desc": "Acompanhe os níveis de nitrogênio, fósforo e potássio com medidores visuais e indicadores de faixa ideal.",
    "features.ai.title": "Recomendações IA",
    "features.ai.desc": "Obtenha sugestões personalizadas de culturas e técnicas de melhoria impulsionadas por IA.",
    "features.multiField.title": "Rastreamento Multi-Campo",
    "features.multiField.desc": "Gerencie múltiplos campos e acompanhe o histórico de saúde do solo com relatórios detalhados.",
    "cta.title": "Pronto para Melhorar Sua Produtividade?",
    "cta.description": "Junte-se a agricultores que tomam decisões baseadas em dados para um solo mais saudável.",
    "cta.createAccount": "Criar Conta Grátis",
    "footer.tagline": "SoilSense — Ajudando agricultores a tomar decisões informadas",
    "dashboard.welcome": "Bem-vindo",
    "dashboard.signOut": "Sair",
    "dashboard.yourFields": "Seus Campos",
    "dashboard.addField": "Adicionar Campo",
    "dashboard.noFields": "Sem campos ainda",
    "dashboard.addFirstField": "Adicione seu primeiro campo para começar",
    "dashboard.selectField": "Selecione um campo para ver relatórios",
    "dashboard.reports": "Relatórios",
    "dashboard.addReport": "Adicionar Relatório",
    "dashboard.noReports": "Sem relatórios ainda",
    "dashboard.addFirstReport": "Adicione seu primeiro relatório para começar",
    "dashboard.analyzeWithAI": "Analisar com IA",
    "dashboard.analyzing": "Analisando...",
    "soil.health": "Saúde do Solo",
    "soil.nitrogen": "Nitrogênio",
    "soil.phosphorus": "Fósforo",
    "soil.potassium": "Potássio",
    "soil.ph": "Nível de pH",
    "soil.organicMatter": "Matéria Orgânica",
    "soil.moisture": "Umidade",
    "soil.temperature": "Temperatura",
    "ai.analysis": "Análise IA",
    "ai.recommendations": "Recomendações",
    "ai.recommendedCrops": "Culturas Recomendadas",
    "ai.improvementTechniques": "Técnicas de Melhoria",
    "ai.seasonalTips": "Dicas Sazonais",
    "ai.npkAnalysis": "Análise NPK",
    "ai.print": "Imprimir",
    "auth.signIn": "Entrar",
    "auth.signUp": "Registrar",
    "auth.email": "Email",
    "auth.password": "Senha",
    "auth.fullName": "Nome Completo",
    "auth.noAccount": "Não tem conta?",
    "auth.haveAccount": "Já tem conta?",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.delete": "Excluir",
    "common.edit": "Editar",
    "common.loading": "Carregando...",
    "common.error": "Erro",
    "common.success": "Sucesso",
    "common.acres": "acres",
    "common.location": "Localização",
    "common.date": "Data",
  },
  fr: {
    "app.title": "KISAAN - Analyseur",
    "app.subtitle": "Lecteur de Rapports d'Engrais",
    "app.getStarted": "Commencer",
    "app.goToDashboard": "Aller au Tableau de Bord",
    "app.loading": "Chargement...",
    "hero.title1": "Comprenez Votre Sol,",
    "hero.title2": "Cultivez de Meilleures Récoltes",
    "hero.description": "Téléchargez vos rapports d'engrais, obtenez une analyse IA et recevez des recommandations personnalisées pour améliorer vos champs.",
    "hero.startFree": "Commencer Gratuitement",
    "hero.viewFields": "Voir Vos Champs",
    "features.title": "Tout Ce Dont Vous Avez Besoin",
    "features.npk.title": "Analyse NPK",
    "features.npk.desc": "Suivez les niveaux d'azote, phosphore et potassium avec des jauges visuelles et des indicateurs de plage optimale.",
    "features.ai.title": "Recommandations IA",
    "features.ai.desc": "Obtenez des suggestions de cultures personnalisées et des techniques d'amélioration propulsées par l'IA.",
    "features.multiField.title": "Suivi Multi-Champs",
    "features.multiField.desc": "Gérez plusieurs champs et suivez l'historique de santé du sol avec des rapports détaillés.",
    "cta.title": "Prêt à Améliorer Vos Rendements?",
    "cta.description": "Rejoignez les agriculteurs qui prennent des décisions basées sur les données pour un sol plus sain.",
    "cta.createAccount": "Créer un Compte Gratuit",
    "footer.tagline": "SoilSense — Aider les agriculteurs à prendre des décisions éclairées",
    "dashboard.welcome": "Bienvenue",
    "dashboard.signOut": "Déconnexion",
    "dashboard.yourFields": "Vos Champs",
    "dashboard.addField": "Ajouter un Champ",
    "dashboard.noFields": "Pas encore de champs",
    "dashboard.addFirstField": "Ajoutez votre premier champ pour commencer",
    "dashboard.selectField": "Sélectionnez un champ pour voir les rapports",
    "dashboard.reports": "Rapports",
    "dashboard.addReport": "Ajouter un Rapport",
    "dashboard.noReports": "Pas encore de rapports",
    "dashboard.addFirstReport": "Ajoutez votre premier rapport pour commencer",
    "dashboard.analyzeWithAI": "Analyser avec IA",
    "dashboard.analyzing": "Analyse en cours...",
    "soil.health": "Santé du Sol",
    "soil.nitrogen": "Azote",
    "soil.phosphorus": "Phosphore",
    "soil.potassium": "Potassium",
    "soil.ph": "Niveau pH",
    "soil.organicMatter": "Matière Organique",
    "soil.moisture": "Humidité",
    "soil.temperature": "Température",
    "ai.analysis": "Analyse IA",
    "ai.recommendations": "Recommandations",
    "ai.recommendedCrops": "Cultures Recommandées",
    "ai.improvementTechniques": "Techniques d'Amélioration",
    "ai.seasonalTips": "Conseils Saisonniers",
    "ai.npkAnalysis": "Analyse NPK",
    "ai.print": "Imprimer",
    "auth.signIn": "Connexion",
    "auth.signUp": "Inscription",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.fullName": "Nom Complet",
    "auth.noAccount": "Pas de compte?",
    "auth.haveAccount": "Déjà un compte?",
    "common.save": "Sauvegarder",
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.acres": "acres",
    "common.location": "Emplacement",
    "common.date": "Date",
  },
  de: {
    "app.title": "KISAAN - Analysator",
    "app.subtitle": "Düngerberichtsleser",
    "app.getStarted": "Loslegen",
    "app.goToDashboard": "Zum Dashboard",
    "app.loading": "Laden...",
    "hero.title1": "Verstehe Deinen Boden,",
    "hero.title2": "Baue Bessere Ernten An",
    "hero.description": "Laden Sie Ihre Düngerberichte hoch, erhalten Sie KI-gestützte Analysen und personalisierte Empfehlungen zur Verbesserung Ihrer Felder.",
    "hero.startFree": "Kostenlos Starten",
    "hero.viewFields": "Ihre Felder Ansehen",
    "features.title": "Alles Was Sie Brauchen",
    "features.npk.title": "NPK-Analyse",
    "features.npk.desc": "Verfolgen Sie Stickstoff-, Phosphor- und Kaliumwerte mit visuellen Messgeräten und optimalen Bereichsindikatoren.",
    "features.ai.title": "KI-Empfehlungen",
    "features.ai.desc": "Erhalten Sie personalisierte Kulturvorschläge und Verbesserungstechniken durch KI.",
    "features.multiField.title": "Multi-Feld-Tracking",
    "features.multiField.desc": "Verwalten Sie mehrere Felder und verfolgen Sie die Bodengesundheitshistorie mit detaillierten Berichten.",
    "cta.title": "Bereit Ihre Erträge zu Verbessern?",
    "cta.description": "Schließen Sie sich Landwirten an, die datenbasierte Entscheidungen für gesündere Böden treffen.",
    "cta.createAccount": "Kostenloses Konto Erstellen",
    "footer.tagline": "SoilSense — Landwirten bei informierten Entscheidungen helfen",
    "dashboard.welcome": "Willkommen",
    "dashboard.signOut": "Abmelden",
    "dashboard.yourFields": "Ihre Felder",
    "dashboard.addField": "Feld Hinzufügen",
    "dashboard.noFields": "Noch keine Felder",
    "dashboard.addFirstField": "Fügen Sie Ihr erstes Feld hinzu",
    "dashboard.selectField": "Wählen Sie ein Feld um Berichte zu sehen",
    "dashboard.reports": "Berichte",
    "dashboard.addReport": "Bericht Hinzufügen",
    "dashboard.noReports": "Noch keine Berichte",
    "dashboard.addFirstReport": "Fügen Sie Ihren ersten Bericht hinzu",
    "dashboard.analyzeWithAI": "Mit KI Analysieren",
    "dashboard.analyzing": "Analysiere...",
    "soil.health": "Bodengesundheit",
    "soil.nitrogen": "Stickstoff",
    "soil.phosphorus": "Phosphor",
    "soil.potassium": "Kalium",
    "soil.ph": "pH-Wert",
    "soil.organicMatter": "Organische Substanz",
    "soil.moisture": "Feuchtigkeit",
    "soil.temperature": "Temperatur",
    "ai.analysis": "KI-Analyse",
    "ai.recommendations": "Empfehlungen",
    "ai.recommendedCrops": "Empfohlene Kulturen",
    "ai.improvementTechniques": "Verbesserungstechniken",
    "ai.seasonalTips": "Saisonale Tipps",
    "ai.npkAnalysis": "NPK-Analyse",
    "ai.print": "Drucken",
    "auth.signIn": "Anmelden",
    "auth.signUp": "Registrieren",
    "auth.email": "E-Mail",
    "auth.password": "Passwort",
    "auth.fullName": "Vollständiger Name",
    "auth.noAccount": "Kein Konto?",
    "auth.haveAccount": "Bereits ein Konto?",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.delete": "Löschen",
    "common.edit": "Bearbeiten",
    "common.loading": "Laden...",
    "common.error": "Fehler",
    "common.success": "Erfolg",
    "common.acres": "Hektar",
    "common.location": "Standort",
    "common.date": "Datum",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as LanguageCode) || 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const languageName = LANGUAGES.find(l => l.code === language)?.nativeName || 'English';

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languageName }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};